[platformio]
src_dir = examples/abm-mini/src

[env]
lib_extra_dirs = ${PROJECT_DIR}/lib/
lib_deps =
    vshymanskyy/TinyGSM @ ^0.10.9
    me-no-dev/ESPAsyncTCP @ ^1.2.2
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESP Async WebServer @ ^1.2.3
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.17.3

[env:esp32doit-devkit-v1]
framework = arduino
platform = espressif32
board = esp32doit-devkit-v1
upload_speed = 921600
lib_deps =
    ${env.lib_deps}
    adafruit/DHT sensor library @ ^1.4.2
    adafruit/Adafruit Unified Sensor @ ^1.1.4
    sui77/rc-switch @ ^2.6.4
;board_build.partitions = huge_app.csv

[env:d1-mini-lite]
framework = arduino
platform = espressif8266
board = d1_mini_lite
upload_speed = 115200
lib_deps =
    ${env.lib_deps}


