[env:ABM_MINI]
framework = arduino
platform = espressif32
board = esp32doit-devkit-v1
upload_speed = 115200
lib_deps =
    ${env.lib_deps}
    viralink/Viralink_Arduino_SDK @ ^0.0.25
    adafruit/DHT sensor library @ ^1.4.1
    adafruit/Adafruit Unified Sensor @ ^1.1.4
